Order tasks alphabetically

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -4,6 +4,20 @@ includes:
   dist: ./DistTasks.yml
 
 tasks:
+  build:
+    desc: Build the project
+    deps:
+      - task: go:build
+
+  check:
+    desc: Check fmt and lint
+    cmds:
+      - test -z $(go fmt ./...)
+      - go vet ./...
+      - task: go:lint
+      - task: config:check
+      - task: general:check-formatting
+
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
   general:cache-dep-licenses:
     desc: Cache dependency license metadata
@@ -28,6 +42,25 @@ tasks:
       - task: general:cache-dep-licenses
     cmds:
       - licensed status
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-general-formatting-task/Taskfile.yml
+  general:check-formatting:
+    desc: Check basic formatting style of all files
+    cmds:
+      - |
+        if ! which ec &>/dev/null; then
+          echo "ec not found or not in PATH."
+          echo "Please install: https://github.com/editorconfig-checker/editorconfig-checker#installation"
+          exit 1
+        fi
+      - ec
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/go-task/Taskfile.yml
+  go:build:
+    desc: Build the Go code
+    dir: "{{.DEFAULT_GO_MODULE_PATH}}"
+    cmds:
+      - go build -v {{.LDFLAGS}}
 
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
   go:fix:
@@ -58,31 +91,6 @@ tasks:
           {{default "-min_confidence 0.8 -set_exit_status" .GO_LINT_FLAGS}} \
           {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
 
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/go-task/Taskfile.yml
-  go:build:
-    desc: Build the Go code
-    dir: "{{.DEFAULT_GO_MODULE_PATH}}"
-    cmds:
-      - go build -v {{.LDFLAGS}}
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
-  go:vet:
-    desc: Check for errors in Go code
-    dir: "{{default .DEFAULT_GO_MODULE_PATH .GO_MODULE_PATH}}"
-    cmds:
-      - go vet {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
-
-  build:
-    desc: Build the project
-    deps:
-      - task: go:build
-
-  test:
-    desc: Run tests
-    cmds:
-      - task: test-unit
-      - task: go:test-integration
-
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/test-go-task/Taskfile.yml
   go:test:
     desc: Run unit tests
@@ -99,26 +107,18 @@ tasks:
           {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}} \
           {{.TEST_LDFLAGS}}
 
-  check:
-    desc: Check fmt and lint
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
+  go:vet:
+    desc: Check for errors in Go code
+    dir: "{{default .DEFAULT_GO_MODULE_PATH .GO_MODULE_PATH}}"
     cmds:
-      - test -z $(go fmt ./...)
-      - go vet ./...
-      - task: go:lint
-      - task: config:check
-      - task: general:check-formatting
+      - go vet {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
 
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-general-formatting-task/Taskfile.yml
-  general:check-formatting:
-    desc: Check basic formatting style of all files
+  test:
+    desc: Run tests
     cmds:
-      - |
-        if ! which ec &>/dev/null; then
-          echo "ec not found or not in PATH."
-          echo "Please install: https://github.com/editorconfig-checker/editorconfig-checker#installation"
-          exit 1
-        fi
-      - ec
+      - task: test-unit
+      - task: go:test-integration
 
 vars:
   PROJECT_NAME: "uno-r4-wifi-fwuploader-plugin"
